### ISSUE TITLE
Contradiction between paper and code

### ISSUE THREAD

**Issue by AlaaBenZekri** [xiyuez2/MapPrior#2]
After trying to understand your work in depth (as it is helpful for a project that I am working on), it seems to me that there is a contradiction between what is stated in the paper and what is done realistically in your code; On one hand, in the paper you mention that the first stage is a predictive stage where you train a model (which is the BEVFusion model) to estimate a first noisy BEV before using it in training another model (that also contains the VQGAN and the transformer). On the other hand, in the code you mention that in the first stage you train an autoencoder (the VQGAN to be precise) and then you would use it in the first stage in training the whole model.
Please correct my understanding if it is wrong. Nevertheless, thanks for your work as it is quite good and it's helping advance this area of research.

**Comment by xiyuez2** [comment]
Sorry for the confusion. There is some gap in the naming between the paper and the codebase. 
In the code, we only use the pre-trained model from bevfusion since this part is unmodified. The first and second "stage" in this codebase refers to the two parts in the generative stage in the paper (i.e. the autoencoder and transformer). Thanks.
